[project]
name = "1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "DavidZakharyan", email = "71030008+DavidZakharyan@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.16.9",
]
